export const SHOP_CATEGORIES = [
  { id: "all", name: "All Categories", count: 11 },
  { id: "accessories", name: "Accessories", count: 4 },
  { id: "cleaning-set", name: "Cleaning Set", count: 3 },
  { id: "clothes", name: "Clothes", count: 3 },
  { id: "equipment", name: "Equipment", count: 2 },
];

export const PRODUCTS_DATA = [
  {
    id: "prod-1",
    title: "Cleaning Fabric",
    category: "accessories",
    categoryName: "Accessories",
    price: 5.00,
    originalPrice: 10.00,
    rating: 5.0,
    reviewsCount: 42,
    isSale: true,
    inStock: true,
    image: "https://qleen.bold-themes.com/demo-01/wp-content/uploads/sites/2/2022/03/product_11.jpg",
    shortDesc: "Ultra-absorbent green patterned microfiber cleaning fabric.",
    description: "Premium lint-free microfiber fabric ideal for cleaning windows, mirrors, countertops, and appliances with water or natural cleaner.",
    features: ["Scratch-free split microfiber", "Machine washable up to 500 times", "Fast drying"]
  },
  {
    id: "prod-2",
    title: "Woman Polo T-shirt",
    category: "clothes",
    categoryName: "Clothes",
    price: 15.00,
    originalPrice: 20.00,
    rating: 4.8,
    reviewsCount: 33,
    isSale: true,
    inStock: true,
    image: "https://qleen.bold-themes.com/demo-01/wp-content/uploads/sites/2/2018/09/product_01.jpg",
    shortDesc: "Official Qleen green staff polo for women.",
    description: "Breathable piqué cotton polo shirt featuring Qleen chest print and tailored fit.",
    features: ["100% organic piqué cotton", "Breathable fabric", "Durable collar"]
  },
  {
    id: "prod-3",
    title: "Protective Mask",
    category: "accessories",
    categoryName: "Accessories",
    price: 5.00,
    originalPrice: 10.00,
    rating: 4.9,
    reviewsCount: 51,
    isSale: true,
    inStock: true,
    image: "https://images.unsplash.com/photo-1584634731339-252c581abfc5?auto=format&fit=crop&w=600&q=80",
    shortDesc: "Reusable green protective face mask with Qleen logo.",
    description: "Washable double-layer cotton protective mask with comfortable elastic ear loops.",
    features: ["Double layer cotton", "Washable & reusable", "Soft elastic loops"]
  },
  {
    id: "prod-4",
    title: "Cleaning Fabric Set",
    category: "accessories",
    categoryName: "Accessories",
    price: 12.00,
    originalPrice: null,
    rating: 4.8,
    reviewsCount: 38,
    isSale: false,
    inStock: true,
    image: "https://qleen.bold-themes.com/demo-01/wp-content/uploads/sites/2/2022/03/product_12.jpg",
    shortDesc: "Set of 3 multi-color premium microfiber cloths.",
    description: "Assorted set of 3 durable microfiber towels designed for color-coded home cleaning without cross-contamination.",
    features: ["Set of 3 distinct colors", "Ultra high density 400 GSM", "Lint free"]
  },
  {
    id: "prod-5",
    title: "Eco Cleaning Set",
    category: "cleaning-set",
    categoryName: "Cleaning Set",
    price: 25.00,
    originalPrice: null,
    rating: 5.0,
    reviewsCount: 89,
    isSale: false,
    inStock: true,
    image: "https://qleen.bold-themes.com/demo-01/wp-content/uploads/sites/2/2018/09/product_07.jpg",
    shortDesc: "Complete starter set of organic sprays and sponges.",
    description: "Our signature eco kit containing plant-based surface spray, natural sponges, glass cleaner, and coconut scrubbers.",
    features: ["100% plant-based formulas", "Includes 2 refill bottles", "Safe around children & pets"]
  },
  {
    id: "prod-6",
    title: "Eco Friendly Brush",
    category: "equipment",
    categoryName: "Equipment",
    price: 8.00,
    originalPrice: 12.00,
    rating: 4.7,
    reviewsCount: 29,
    isSale: true,
    inStock: true,
    image: "https://qleen.bold-themes.com/demo-01/wp-content/uploads/sites/2/2018/09/product_08.jpg",
    shortDesc: "Ergonomic wooden dish & surface scrub brush.",
    description: "Sustainably harvested beechwood handle with stiff plant bristles designed to scrub pots, pans, and stubborn sink grime.",
    features: ["Natural sisal bristles", "Ergonomic comfortable grip", "100% compostable handle"]
  },
  {
    id: "prod-7",
    title: "Green Bag",
    category: "accessories",
    categoryName: "Accessories",
    price: 14.00,
    originalPrice: null,
    rating: 4.9,
    reviewsCount: 54,
    isSale: false,
    inStock: true,
    image: "https://qleen.bold-themes.com/demo-01/wp-content/uploads/sites/2/2018/09/product_05.jpg",
    shortDesc: "Reusable green tote bag with Qleen emblem.",
    description: "Heavy-duty 100% organic canvas tote bag for carrying cleaning supplies, groceries, or everyday essentials.",
    features: ["Reinforced handles", "100% organic cotton", "Eco friendly print"]
  },
  {
    id: "prod-8",
    title: "Orange Cap",
    category: "clothes",
    categoryName: "Clothes",
    price: 10.00,
    originalPrice: null,
    rating: 4.7,
    reviewsCount: 15,
    isSale: false,
    inStock: true,
    image: "https://qleen.bold-themes.com/demo-01/wp-content/uploads/sites/2/2018/09/product_02.jpg",
    shortDesc: "Vibrant orange cotton cap with Qleen logo.",
    description: "Bright signature orange baseball cap with embroidered Qleen emblem.",
    features: ["Vibrant orange color", "Adjustable strap", "Lightweight design"]
  },
  {
    id: "prod-9",
    title: "Man Polo T-shirt",
    category: "clothes",
    categoryName: "Clothes",
    price: 15.00,
    originalPrice: null,
    rating: 4.9,
    reviewsCount: 47,
    isSale: false,
    inStock: true,
    image: "https://qleen.bold-themes.com/demo-01/wp-content/uploads/sites/2/2018/09/product_03.jpg",
    shortDesc: "Official Qleen green staff polo for men.",
    description: "Classic fit men's polo shirt crafted from soft breathable cotton with embroidered Qleen chest logo.",
    features: ["Classic relaxed fit", "Reinforced stitching", "Machine washable"]
  },
  {
    id: "prod-10",
    title: "Green Cap Uniform",
    category: "clothes",
    categoryName: "Clothes",
    price: 10.00,
    originalPrice: null,
    rating: 4.6,
    reviewsCount: 19,
    isSale: false,
    inStock: true,
    image: "https://qleen.bold-themes.com/demo-01/wp-content/uploads/sites/2/2018/09/product_09.jpg",
    shortDesc: "Adjustable green cotton baseball cap with embroidered logo.",
    description: "Comfortable breathable cotton cap worn by our professional staff and available for Qleen enthusiasts.",
    features: ["Adjustable brass buckle", "100% twill cotton", "Embroidered front logo"]
  },
  {
    id: "prod-11",
    title: "Protective Apron",
    category: "equipment",
    categoryName: "Equipment",
    price: 18.00,
    originalPrice: null,
    rating: 4.8,
    reviewsCount: 22,
    isSale: false,
    inStock: true,
    image: "https://qleen.bold-themes.com/demo-01/wp-content/uploads/sites/2/2018/09/product_06.jpg",
    shortDesc: "Durable waterproof cleaning apron.",
    description: "Heavy-duty adjustable neck strap apron with front utility pockets.",
    features: ["Waterproof canvas", "Dual front pockets", "Adjustable neck strap"]
  }
];
